# Generated by Django 3.1 on 2020-09-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='type',
            field=models.CharField(default='lecture', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_server.courseclass'),
        ),
    ]
