# Generated by Django 3.1 on 2020-09-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0002_auto_20200901_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='index',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
