# Generated by Django 3.1 on 2020-09-01 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance_server', '0003_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='teachers',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
