# Generated by Django 3.1 on 2020-09-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0004_auto_20200902_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='teachers',
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_server.courseclass')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_server.teacherprofile')),
            ],
        ),
    ]
