# Generated by Django 3.1 on 2020-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0005_auto_20200902_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='time',
            new_name='open_time',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
