# Generated by Django 3.1 on 2020-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0007_coursestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
