# Generated by Django 3.1 on 2020-09-18 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0009_attendance_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='open_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 16, 45, 3, 53760)),
        ),
    ]
