# Generated by Django 3.1 on 2020-10-10 04:18

import attendance_server.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0010_auto_20200918_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='face_recognition',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=attendance_server.models.image_path),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='open_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 12, 18, 57, 973524)),
        ),
    ]
