# Generated by Django 3.1 on 2020-10-01 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0010_auto_20200918_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='open_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
