# Generated by Django 3.1 on 2020-10-13 07:23

import attendance_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_server', '0011_auto_20201001_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='face_recognition',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=attendance_server.models.image_path),
        ),
    ]
